### ISSUE TITLE
pf_ring does not compile with 4.15

### ISSUE THREAD

**Issue by roheline** [cert-ee/s4a#20]
```
DKMS make.log for pfring-7.1.0 for kernel 4.15.0-33-generic (x86_64)
Mon Sep 10 11:16:50 EEST 2018
make -C /lib/modules/4.15.0-33-generic/build SUBDIRS=/var/lib/dkms/pfring/7.1.0/build EXTRA_CFLAGS='-I/var/lib/dkms/pfring/7.1.0/build -DGIT_REV="\"dev:057c34e02316b4895bc242ee391b81bb60c5eb1f\""' modules
make[1]: Entering directory '/usr/src/linux-headers-4.15.0-33-generic'
  CC [M]  /var/lib/dkms/pfring/7.1.0/build/pf_ring.o
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c: In function ‘skb_ring_handler’:
/var/lib/dkms/pfring/7.1.0/build/pf_ring.c:3948:38: error: implicit declaration of function ‘ACCESS_ONCE’ [-Werror=implicit-function-declaration]
       u_short num_cluster_elements = ACCESS_ONCE(cluster_ptr->cluster.num_cluster_elements);
                                      ^
cc1: some warnings being treated as errors
scripts/Makefile.build:339: recipe for target '/var/lib/dkms/pfring/7.1.0/build/pf_ring.o' failed
make[2]: *** [/var/lib/dkms/pfring/7.1.0/build/pf_ring.o] Error 1
Makefile:1552: recipe for target '_module_/var/lib/dkms/pfring/7.1.0/build' failed
make[1]: *** [_module_/var/lib/dkms/pfring/7.1.0/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-4.15.0-33-generic'
Makefile:50: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by voldemarpanso** [comment]
As far as I'm concerned you are just using outdated deb, use the one built at least against pfring 7.2.0
But while investigating the issue Razu suggested to fix pfring's version, hopefully we'll avoid some
issues in the future
Also removed some minor obsolete build tunings assuming you are not building older Suricata than 4.0.5.
See #21
